<?php

class OptionsTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('options')->delete();

        $options = array(   array('title' => 'PopCorn Developer', 'description' => 'Challenge 1A\nHow can we make information about businesses (e.g. business hours, types of business, rates for different types of business, location) in the community more accessible to all Singaporeans?', 'poll_id' => 1,  'school' => 'NYP', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'RAYC', 'description' => 'Challenge 1A\nHow can we make information about businesses (e.g. business hours, types of business, rates for different types of business, location) in the community more accessible to all Singaporeans?', 'poll_id' => 2,  'school' => 'TEMASEK POLYTECHNIC', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Geo-Dude', 'description' => 'Challenge 1B\nHow can we reach out to the volunteers in our community for social welfare programmes and volunteering opportunities?', 'poll_id' => 3,  'school' => 'Hwa Chong Junior College', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'NUS-0313', 'description' => 'Challenge 2A\nHow can we improve mobility for the disabled in Pasir Ris Town?', 'poll_id' => 4,  'school' => 'National University of Singapore', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Infocomm & Network Engineering', 'description' => 'Challenge 2A\nHow can we improve mobility for the disabled in Pasir Ris Town?', 'poll_id' => 5,  'school' => 'TEMASEK POLYTECHNIC', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Layo', 'description' => 'Challenge 2B\nHow can we better reach out to those (e.g. needy families , the aged/elderly) in need of assistance?', 'poll_id' => 6,  'school' => 'ITE COLLEGE EAST', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'APEX', 'description' => 'Challenge 2C\nHow can we help the residents in my community better understand the history and heritage of Pasir Ris (e.g. from a swamp to a town)?', 'poll_id' => 7,  'school' => 'Temasek Junior College', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'SAINTS', 'description' => 'Challenge 3A\nWe would like to motivate and encourage our mobile senior citizens who are living alone to participate in our activities. Give us recommendations based on your analysis.', 'poll_id' => 8,  'school' => 'St. Andrew\'s Junior College', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Financial Business Informatics', 'description' => 'Challenge 3A\nWe would like to motivate and encourage our mobile senior citizens who are living alone to participate in our activities. Give us recommendations based on your analysis.', 'poll_id' => 9,  'school' => 'TEMASEK POLYTECHNIC', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Team Spatiality', 'description' => 'Challenge 3B\nWe would like to extend our social services and assistance to the senior citizens living in our community; especially our seniors who are living alone. Our challenge to you – suggest means for us to connect/check-up on these seniors who are living alone based on your observation/analysis.', 'poll_id' => 1,  'school' => 'Hwa Chong Junior College', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Earthbound', 'description' => 'Challenge 3E\nCelebrating Moulmein’s Local Heritage - Little India Heritage Trial\nHow can we provide links to information sources on the many heritage sites in India for local and visiting tourists.', 'poll_id' => 11,  'school' => 'Singapore Polytechnic', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Team Geonovation', 'description' => 'Challenge 4B\nWe would like to create a township application that will have all the information on single elderly staying alone, event listing, latest improvement work. We would provide the data for the students to piece them together into an app.', 'poll_id' => 12,  'school' => 'NYP', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'YOLO', 'description' => 'Challenge 5D/nHow can we promote a healthy lifestyle amongst students?', 'poll_id' => 13,  'school' => 'Republic Polytechnic', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Fantastic', 'description' => 'Challenge 5E\nHow can we promote a healthy lifestyle amongst working adults?', 'poll_id' => 14,  'school' => 'ITE college west', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Team Innovate', 'description' => 'Challenge 5E\nHow can we promote a healthy lifestyle amongst working adults?', 'poll_id' => 15,  'school' => 'Innova Junior College', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Team DMSD', 'description' => 'Challenge 5G\nHow can we create a solution for students to find out which community service projects/events they would like to participate in?', 'poll_id' => 16,  'school' => 'Republic Polytechnic', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'DTX', 'description' => 'Challenge 5H\nHow can we create a solution where residents can find out the location of facilities (civic amenities, police, recycling collection centres, markets etc.. for themselves.', 'poll_id' => 17,  'school' => 'NYP', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'ALS', 'description' => 'Challenge 6A\nHow can we help the residents in Nee Soon community find out more information about our Volunteer Welfare Organisations (VWOs) and encourage them to participate more actively in community involvement programmes?*main aim: VWO mapping', 'poll_id' => 18,  'school' => 'NYP', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'The Joggers', 'description' => 'Challenge 6A\nHow can we help the residents in Nee Soon community find out more information about our Volunteer Welfare Organisations (VWOs) and encourage them to participate more actively in community involvement programmes?*main aim: VWO mapping', 'poll_id' => 19,  'school' => 'Raffles Institution', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Epsilon', 'description' => 'Challenge 6B\nHow can we help organisations/residents in Nee Soon community to locate places with informal community activities or possible spaces for various communal use? *main aim: communal space mapping', 'poll_id' => 20,  'school' => 'National Junior College', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Team AAA', 'description' => 'Challenge 6B\nHow can we help organisations/residents in Nee Soon community to locate places with informal community activities or possible spaces for various communal use? *main aim: communal space mapping', 'poll_id' => 21,  'school' => 'Republic Polytechnic', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Gneiss Guys', 'description' => 'Challenge 7B\nHow can we measure or improve awareness of Emergency Preparedness measures for Thomson community residents?', 'poll_id' => 22,  'school' => 'Raffles Institution', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Mantis', 'description' => 'Challenge 7C\nHow can we get people to experience and understand the rich heritage and modern quirks of the Bishan, Toa Payoh and Thomson estates?', 'poll_id' => 23,  'school' => 'Singapore Polytechnic', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Team Fabulous', 'description' => 'Challenge 7C\nHow can we get people to experience and understand the rich heritage and modern quirks of the Bishan, Toa Payoh and Thomson estates?', 'poll_id' => 24,  'school' => 'Raffles Institution', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'LKZ', 'description' => 'Challenge 8A\nIdentifying and grouping information from communication bursts at Yuhua - The team which has chosen this project task has to find out how and what type of information, eg: events, environmental concerns/hazards, assistance schemes etc, are communicated at the community level and identify locations and ways in which different information can be disseminated with better awareness and response rate within Yuhua.', 'poll_id' => 25,  'school' => 'ITE college west', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'RGIS', 'description' => 'Challenge 8C\nIdentifying and grouping residents from activities at the Yuhua Community Club - The team which has chosen this project task will need to find out for activities organised by Yuhua CC, which are the predominant participant profiles for each activity to see if there is a spatial pattern to it. The team can then suggest, based on the profile and area of participants, types of activities that will appeal for different communities in Yuhua.', 'poll_id' => 26,  'school' => 'SMU', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Team NUS High', 'description' => 'Challenge 8C\nIdentifying and grouping residents from activities at the Yuhua Community Club - The team which has chosen this project task will need to find out for activities organised by Yuhua CC, which are the predominant participant profiles for each activity to see if there is a spatial pattern to it. The team can then suggest, based on the profile and area of participants, types of activities that will appeal for different communities in Yuhua.', 'poll_id' => 27,  'school' => 'NUS HIGH SCHOOL OF MATHEMATICS AND SCIENCE', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Leagues of Republic', 'description' => 'Challenge 8C\nIdentifying and grouping residents from activities at the Yuhua Community Club - The team which has chosen this project task will need to find out for activities organised by Yuhua CC, which are the predominant participant profiles for each activity to see if there is a spatial pattern to it. The team can then suggest, based on the profile and area of participants, types of activities that will appeal for different communities in Yuhua.', 'poll_id' => 28,  'school' => 'Republic Polytechnic', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'Map Our Lives', 'description' => 'Challenge 9B\nUnderstanding local traffic conditions', 'poll_id' => 29,  'school' => 'NYP', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => '#TeamKM', 'description' => 'Challenge 9C\nEncourage community bonding', 'poll_id' => 30,  'school' => 'NYP', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'),
                            array('title' => 'RedDot', 'description' => 'Challenge 9B\nEncourage community bonding', 'poll_id' => 31,  'school' => 'NYP', 'image' => 'http://www.lithpiratestravelbaseball.com/sites/default/files/styles/large/public/team-pics/pirates-13u-team-photo-placeholder-2013.jpg?itok=Nmeh3udN'));

        \Option::insert($options);
    }

}